### ISSUE TITLE
Drop doesn't work

### ISSUE THREAD

**Issue by HapLifeMan** [hejianxian/vddl#18]
Hey,

Thank you for your amazing plugin, it works well but I am encountering an issue when trying to drop a draggable element over a list...

The following code triggers `dragstart`, `dragend` and `dragover` methods but nothing happens on `drop` event... Any idea?

```blade
<vddl-list :list="self.cards.hand" :horizontal="true">
    <vddl-draggable v-for="(card, index) in self.cards.hand" :index="index" :wrapper="self.cards.hand" @dragstart="testDragStart" :draggable="card">
        <img v-bind:src="'/assets/img/full_cards/' + card.id + '.png'" />
    </vddl-draggable>
</vddl-list>
```

```blade
<vddl-list @drop="testDrop" list="testArr"></vddl-list>
```

```js
var vueData = {
    testArr: [],
    self: {
        cards: {
            hand: [],
```

I am using Vddl by importing the main .js file (I know that's very dirty)...

Thanks for your help 😊

**Comment by hejianxian** [comment]
@HapLifeMan Thank you!

```html
<vddl-list @drop="testDrop" list="testArr"></vddl-list>
```
Something wrong here, it should be written like this:
```
<vddl-list :drop="testDrop" list="testArr"></vddl-list>
```

**Comment by hejianxian** [comment]
@HapLifeMan Thank you!

At first, is the `drop` callback not triggered? Maybe you can look this [simple demo source](https://github.com/hejianxian/vddl/blob/master/example/src/views/simple.vue).

Second, if you set the `drop` callback in `vddl-list`, you will have to splice the `:list` yourself.

```js
handleDrop(data) {
  const { index, list, item } = data;
  list.splice(index, 0, item);
},
```
[#L120](https://github.com/hejianxian/vddl/blob/master/example/src/views/simple.vue#L120)

**Comment by HapLifeMan** [comment]
The `drop` callback isn't triggered, I'll try with handleDrop!
I try almost everything possible from your documentation 😅

**Comment by HapLifeMan** [comment]
`handleDrop` doesn't work :(

**Comment by hejianxian** [comment]
@HapLifeMan 😢 

Give me more info! your code, browser, and `vddl` version?

**Comment by HapLifeMan** [comment]
Here's the repo with the issue: [HapLifeMan/vddl-test](https://github.com/HapLifeMan/vddl-test)!

**Comment by hejianxian** [comment]
@HapLifeMan 

```html
<div style="background-color: blueviolet; width: 300px; height: 300px;">
    <vddl-list :drop="dropEvent" :list="cards2" style="width: 100%; height: 100%;"></vddl-list></div>
```

Not use '@' with drop callback.

**Comment by HapLifeMan** [comment]
Is that work on your side?
I tried with `:drop` but nothing happens, `dropEvent` not triggered... I updated the repo!

**Comment by hejianxian** [comment]
I tried your demo, if used `:drop`, the `dropEvent` triggered when drop a draggable element to the `list`.

I think, in fact, do you need the `dragover` callback? The `drop` callback just trigger when drop an element to the `vddl-list`;

**Comment by HapLifeMan** [comment]
I have a list of draggable elements, I want to drag&drop these elements on 5 "single-lists" (= vddl-list that can contain only 1 draggable element but still dragable&dropable).

**Comment by hejianxian** [comment]
Maybe you need 5 single list, like:

```html
<vddl-list>
    <vddl-draggable></vddl-draggable>
</vddl-list>
```
And then, set some conditions to limit draggable items number.

**Comment by HapLifeMan** [comment]
Of course that's what I did but nothing is triggered on drop :/

**Comment by HapLifeMan** [comment]
After some tests, Vddl wasn't initialized and native HTML5 drag event was triggered.

I finally solve this problem after maaaanyyyyyyy (not sure if it's enough) hours of work by adding `DragAndDropList.install(Vue);` before instantiating Vue.

Wow, that was a real brainfuck, and the solution really ridiculous.
Hope that'll help people in the future!
