### ISSUE TITLE
Is there a way to get parent container ID when dropping items?

### ISSUE THREAD

**Issue by AWulkan** [hejianxian/vddl#19]
This is more of a question than an issue.

Let's say I have a nested list. I then drag an item from one container to another. Is there any way to see the ID of the container I dropped the item in?

Right now I only get information about the item's ID and the containers list in the `inserted` callback.

**Comment by mlapeyre3** [comment]
Hi @AWulkan, did you find a solution (or a workaround) of your issue? I have the same question!
Thanks

**Comment by hejianxian** [comment]
It may be possible to add the `containerId` attribute to the `item` data.
