### ISSUE TITLE
Tree View support?

### ISSUE THREAD

**Issue by syska** [hejianxian/vddl#2]
This looks awesome ... I'm looking for something like this and it's the best for VueJs I have found yet.

But I'm looking for something a little different. I need to edit a tree view of nodes and move them around like the container part ...

Something like this, besides it's for angularjs: https://angular-ui-tree.github.io/angular-ui-tree/#/basic-example 

Is that a big new thing for vddl or could this be easily implemented ... I can see most of the stuff is supported in some way already.

**Comment by hejianxian** [comment]
@syska Thank you! 

I'm not quite sure. But if the elements from the layout to do some changes, it should be able to achieve the effect of tree. Or, I can try to write a tree demo later.

**Comment by hejianxian** [comment]
How about this. [vue-drag-tree](https://github.com/shuiRong/vue-drag-tree)

**Comment by syska** [comment]
@hejianxian 

Would be awesome with a demo if possible ...

**Comment by syska** [comment]
Thinking about it ... I guess I could style this: http://hejx.space/vddl-demo/#/nested
