### ISSUE TITLE
How to use it with script tag like vuejs

### ISSUE THREAD

**Issue by ajeetku** [hejianxian/vddl#20]
we use vue js lib with script tag //cdnjs.cloudflare.com/ajax/libs/vue/2.5.2/vue.min.js or download and attach only main file

but in this lib we are integrating this lib it gives
[Vue warn]: Unknown custom element: <vddl-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Same issue for other tags also..
Please guide how can we use your library

**Comment by hejianxian** [comment]
@ajeetku Update `vddl` to v0.7.1
