### ISSUE TITLE
哪个判断代码可以支持拖拽到文件夹头部插入到内容？

### ISSUE THREAD

**Issue by yyman001** [hejianxian/vddl#32]
哪个判断代码可以支持拖拽到文件夹头部插入到内容？

**Comment by hejianxian** [comment]
不太明白你说的问题，可以举个例子吗？

**Comment by yyman001** [comment]
我简单说下：
用官方的demo
http://hejx.space/vddl-demo/#/simple
有List A，List B，List C，现在的拖拽只能往他们的content放会出出现效果，如果直接拖拽到ListA头部的时候，能不能自动计算放入位置为当前ListA的content？
