### ISSUE TITLE
Ugly Flickering effect?

### ISSUE THREAD

**Issue by ChadTaljaardt** [hejianxian/vddl#44]
Hello, 

I'll start off by saying that this is a great tool, I am using it in many different places in my project!

I'm having an issue when I click and drag the field I want to move, I get this ugly hovering effect that flickers. 

I have attached a video of the issue is getting, would you be able to assist in helping me fix this?

Thanks!

https://cl.ly/0s123d3a0O1x

**Comment by hejianxian** [comment]
@ChadTaljaardt Thank you!

In my opinion, try to increase the height of the placeholder and keep it the same as the height of the dragging element.

**Comment by ChadTaljaardt** [comment]
I’ll give it a shot!

**Comment by ChadTaljaardt** [comment]
Great, thanks this has worked!
